language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
notifications:
  slack:
    secure: iqEC8aK4dha8Fn/W1CCfk8gpp9/caRYp04T9HXA3Mu6Q+q11iZBb9G2RTDLetHJAIafAgiAlddWwnrv8FF4yZB9LkKRMScdTNa1CfVhPCGm3/Mv9FUBo9a4cFkpfmI75zI98e7S3MLUfgaNoziZh7x1t0rfoyJ7bBT6YxpkFpmoq+CqGOu7gTCAxE70sQY+aOtCCMHw3oRysLcVuHAnYo2HzcCbeltd8eNM2pEbFuxEeYOMfqVmbkbC2PzVLfrwL4kE3/oAwNiVtFT1jOOP12TquEMooeGr+x7viXbuOvxdG89Do7tmeidD0x/NWK2YCEqxhkJX593zUz8PGep6rXY04kC8DqPlsiqWIDvjLqKCHOSrVwwaRZNlHbex69yExbkkoK7Gf6t6mHy0kCPWgvOv65oh5hxT8ZP4tPz906UYx/5OW4ED1b2bUVT/ECVoYEMyrJcN3ZjZod/XJ+G6vrQMKQAartplzQmpfRThThVdzxRzCbSwxY7Si64941Ugu7Hkvrh7F3A2nazJLEO1zh3csBnZDd9ZEyGhRqV8cmpaJDCKESU49CXGLXga/UIIVV7ORI83URWOgREfGMywA0Fpz6BEdFu5Cp8R1jkYgmWlPo05aqWdUJa1TK42NpFZHqP0K0cRE119odUJweqyMKVAaP4M94Lhv/Jl93R1enMM=
    on_success: change
    on_failure: always
